### ISSUE TITLE
box-sizing trouble

### ISSUE THREAD

**Issue by kamiram** [jackmoore/colorbox#346]
if project css has some like:

``` css
div{
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -webkit-box-sizing: border-box;
}
```

box dusplays without part of border.

it's can be  easy to repair by:

``` css
#colorbox {
    box-sizing: content-box;
    -moz-box-sizing: content-box;
    -ms-box-sizing: content-box;
    -webkit-box-sizing: content-box;
}
```
